# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R Build and Checks
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        r-version: [3.6]
    steps:
    - uses: actions/checkout@v1
    - name: Set up R ${{ matrix.r-version }}
      uses: r-lib/actions/setup-r@ffe45a39586f073cc2e9af79c4ba563b657dc6e3
      with:
        r-version: ${{ matrix.r-version }}
    - name: R Build and Checks
      uses: hechth/R-actions@v1.2.2
      with:
        action: 'all'
        needsBioc: true
        buildSubDirectory: apLCMS
