# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R Build and Checks
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.0.3'
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -yq libfreetype6-dev libglu1-mesa-dev libnetcdf-dev libpng-dev zlib1g-dev
      shell: bash
    - name: Cleanup
      run: sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/*
      shell: bash
    - name: R Build
      run: R CMD build ./apLCMS
      shell: bash
    - name: R Check
      run: R CMD check apLCMS_6.6.6.tar.gz
      shell: bash
