# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R Build and Checks
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.0.3'
    - name: R Build and Checks
      uses: hechth/R-actions@880945e4464e26d88843ee4bb909208bd301964e
      with:
        action: 'all'
        needsBioc: true
        buildSubDirectory: apLCMS
